" Initialize Plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/aleddavies/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Initialize Plugins
call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'ayu-theme/ayu-vim'
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'preservim/nerdcommenter'
Plug 'editorconfig/editorconfig-vim'
Plug 'w0rp/ale'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'junegunn/goyo.vim'
Plug 'tpope/vim-abolish'
Plug 'jdkanani/vim-material-theme'
Plug 'jiangmiao/auto-pairs'
Plug 'frazrepo/vim-rainbow'
call plug#end()

" Map leader to ,
let mapleader = "-,"

" Don't display filename on startup
set shortmess=F

" Enable Terminal Colors
set termguicolors

" Set the color scheme
syntax enable
set background=dark
colorscheme material-theme

" Set Tabs and ident to 2. Expand tabs to space
set tabstop=2 shiftwidth=2 expandtab

" Ensure that the modeline is always visible
set laststatus=2

" Enable line numbers
set number

" Don't show the mode
set noshowmode

" Set lightime theme  
let g:lightline = {
      \ 'colorscheme': 'material',
      \ }

" Map ; to fzf
map ; :Files<CR>

" Toggle NerdTree
map <C-n> :NERDTreeToggle<CR>

" Remove trailing white space
autocmd BufWritePre *.py :%s/\s\+$//e

" Enable Rainbox Parentheses
let g:rainbow_active = 1
